language: java
notifications:
  slack:
    secure: J0FKY1NkRcueFh8NEQGXP5MCa+d3KHC0RpqVQRxcOb49GKIfizVC7pTcfvVR+lPRkL7wqe0UNYLJGEGWQNOnk3uWWDUibf8SuVrQm/6MsG9Y5hRIkAmWG65j6w+Xzx+d+Q15gAC1yoRs/a9bt0uVi/FiXUYTsAM2A2U+sJtZ8yoyTArDrJjywlZSSG7+4xRIHGslTb6MXNu6AvxVqnPTC+0UFa81+s0icVqxg15Y91KI3sytUWsVqa7GI9kCwwdZc+jId0GMlgnRryklcMOKdbqN+Bu/3AFSqiXgBxbutXRJ1n6EKaWBiJNj3Hy9rq/WNAsowUQlBVELN+VJRCIhcW7Yzs/SGSrwEruVJEAD4qxJ/qRpOXkhYc7ZqgIXncosWXY9zQ6w327bPwA2vxBMNtBvBq0s/YBxfVsMCq09nxdQEPkx5VB/mttyjMc3Sjs2PuKOwkkHiqm3VqKHw+ukynCEKK+Aw5r0qWEZLi1TX98Au2TJMOOg+XxAtoQ5uuQI/501DF1KCNKN3iw+AJ/zRC7dw1XXmAedvWQuaVywC9mwMkd8MIx9uVKZ2RWcdO4L3PCElqisnhDGpxDYHfQ9eB8YWTPH2exqIdCK3HlZ+mi5q7Nh+yCtzawgGF3M+EPxwLniAKSDOdihXyUWefRBfMpKgu5JHkTldUENN2Ihi+I=
deploy:
  provider: releases
  api_key:
    secure: yC+LlZctx74yJ7rDzgCixuD/MhhnmXaiK+kZbdYtpERUHIxqLmt18MxTcmasvVGcqfUh5Q9daF16eN6hkQ1H4Q1h6bcVMpP5KRkq3FoMBXPl+6wyETu+fzm8OAhHBhXO4iCy7VDz4Hw7sr15BlR5POsgt9nFGG8164pe4m9Aq44hbRSzdxYhV8XJDcy3O0sDo3RbhtJ65mdd7Biq8ChsvPISf50TrFwk0LC+8D0sr7vbG4uvq4Rs0FPupixBwthKMGz/l6X6wy02Mv30eHeNsoEpcoxGaMgAyjt0tGo9jMeX3UGCWXDJ5XvMgNe3p1oGiaR06GZbEOxqNB80JPfZSiDE51jwWimeQ1JdMt6ORqiY50FIS7I6okKqQ1K3C5ZhsK4E84Z3p1JApiAwCF23xHMp3ejtRngyBvH/h2aomCNJSZDVMwIjRqcIO78cFL4k+miJuE62Hop3wZJOk+l0Oplp96DZ38ZXsW/3fV+6iWNOmoCTkroPBF9aNazl6Kpj3ILhv664GhAPBRCPJ5kDhs1/SU3N/k/K6Ini7bxI/PBppWbm9t10mzHNBQ3LtIuCYh7eS8t0ZgHVae5qCHNtctw3VdXKnVZb2Ws1c4CGbF614rLYm4LsP0hAmrzXjCBYFgu2Kl5dpKIEFKISkoecb6N2Mi5YeV5IjZFRBKBFoBY=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-websphere-portal-plugin
