language: java
notifications:
  hipchat:
    rooms:
      secure: BRxyikZ3/l8yGg63JU/oa7YETcMUhcHXQHFf4EF7kdD4hSgqhmHHlCMjDFcx84rTTf1CrcpiKVJfn1LPFADKr3QMEaatx9nWCPs1iHbZBfRhUJPVaG/1kN0cVyU5vz0v2KY2hx5FTnoecvL6ihdhpnWoWPZZxfDGT7t6uhAElbg=
deploy:
  provider: releases
  api_key:
    secure: yC+LlZctx74yJ7rDzgCixuD/MhhnmXaiK+kZbdYtpERUHIxqLmt18MxTcmasvVGcqfUh5Q9daF16eN6hkQ1H4Q1h6bcVMpP5KRkq3FoMBXPl+6wyETu+fzm8OAhHBhXO4iCy7VDz4Hw7sr15BlR5POsgt9nFGG8164pe4m9Aq44hbRSzdxYhV8XJDcy3O0sDo3RbhtJ65mdd7Biq8ChsvPISf50TrFwk0LC+8D0sr7vbG4uvq4Rs0FPupixBwthKMGz/l6X6wy02Mv30eHeNsoEpcoxGaMgAyjt0tGo9jMeX3UGCWXDJ5XvMgNe3p1oGiaR06GZbEOxqNB80JPfZSiDE51jwWimeQ1JdMt6ORqiY50FIS7I6okKqQ1K3C5ZhsK4E84Z3p1JApiAwCF23xHMp3ejtRngyBvH/h2aomCNJSZDVMwIjRqcIO78cFL4k+miJuE62Hop3wZJOk+l0Oplp96DZ38ZXsW/3fV+6iWNOmoCTkroPBF9aNazl6Kpj3ILhv664GhAPBRCPJ5kDhs1/SU3N/k/K6Ini7bxI/PBppWbm9t10mzHNBQ3LtIuCYh7eS8t0ZgHVae5qCHNtctw3VdXKnVZb2Ws1c4CGbF614rLYm4LsP0hAmrzXjCBYFgu2Kl5dpKIEFKISkoecb6N2Mi5YeV5IjZFRBKBFoBY=
  file_glob: true
  file: build/distributions/*
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-websphere-portal-plugin
